name: Workflow for building and running some simple hardware tests
on: [push]
env:
  LAGER_GATEWAY: 45
concurrency: 
  group: dut
  cancel-in-progress: false

jobs:
  build_and_flash:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Build and Flash Project
        uses: docker://lagerdata/devenv-esp32:version-1.0
        with:
          entrypoint: lager
          args: exec build_and_flash -u root


