name: Workflow for building and running some simple hardware tests
on: [push]
env:
  LAGER_GATEWAY: 45
concurrency: 
  group: dut
  cancel-in-progress: false

jobs:
  build_and_flash:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Build and Flash Project
        uses: docker://lagerdata/devenv-esp32:version-1.0
        env:
          LAGER_TOKEN_ID: ${{ secrets.LAGER_TOKEN_ID }} 
          LAGER_TOKEN_SECRET: ${{ secrets.LAGER_TOKEN_SECRET }}        
        with:
          entrypoint: lager
          args: exec build_and_flash -u root

      - name: Upload test
        uses: actions/upload-artifact@v2
        with:
          name: hello_world_test
          path: tests/test.py

  test: #test basic BLE functionality
    runs-on: ubuntu-latest
    needs: [build_and_flash]
    steps:
      - name: Download test script
        uses: actions/download-artifact@v2
        with:
          name: hello_world_test

      - name: Test Hello World
        uses: docker://lagerdata/lager-cli
        env:
          LAGER_TOKEN_ID: ${{ secrets.LAGER_TOKEN_ID }} 
          LAGER_TOKEN_SECRET: ${{ secrets.LAGER_TOKEN_SECRET }}
        with:
          entrypoint: lager
          args: python test.py